HomeWork2 Done
Idzumikatsu/gb-homeworks pull request #10
Opened 2022-01-13 22:39 UTC by Idzumikatsu

2022-01-13 22:45 UTC, Idzumikatsu commented on src/main/java/LevelTwoJava/HomeWork2/MyArrayDataException.java
> +public class MyArrayDataException extends RuntimeException {
Как я понял, здесь должен быть какой-то переопределенный конструктор?

2022-01-15 08:57 UTC, efserg requested changes

2022-01-15 08:57 UTC, efserg commented on src/main/java/LevelTwoJava/HomeWork2/App.java
> +                System.out.println("Ошибка размера массива! Программа принимает на вход двумерный массив только с размерностью [4][4]. Описание ошибки: " + Arrays.toString(e.getStackTrace()));
Мозг у меня ломается от таких конструкций. Сначала бросать исключение, потом тут его ловить - это выше моего понимания. Вот это работает точно также
```
if (outside != 4 || inside != 4) {
       System.out.println("...
       System.exit(1)
```
Исключение бросаете только потому, что так написано в задании?

2022-01-15 08:57 UTC, efserg commented on src/main/java/LevelTwoJava/HomeWork2/App.java
> +                    number = Integer.parseInt(array[i][j]);
А почему NumberFormatException  должен ловиться MyArrayDataException? Пишите в catch NumberFormatException и все поймается.

2022-01-15 08:57 UTC, efserg commented on src/main/java/LevelTwoJava/HomeWork2/MyArrayDataException.java
> +public class MyArrayDataException extends RuntimeException {
Можно, если он необходим

2022-01-28 08:05 UTC, merged